name: kart_support
description: Utils to support kart, a Kotin to Dart compiler
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  kernel: ^0.3.29
  front_end: any # kernel depends on front_end without declaring a dependency in its pubspec

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
